namespace MilpManager.Abstraction
{
    public enum OperationType
    {
        AbsoluteValue,
        Addition,
        BinaryNegation,
        Condition,
        Conjunction,
        DifferentValuesCount,
        Disjunction,
        Division,
        Equivalency,
        ExclusiveDisjunction,
        Exponentiation,
        GCD,
        Factorial,
        IsEqual,
        IsGreaterOrEqual,
        IsGreaterThan,
        IsLessOrEqual,
        IsLessThan,
        IsNotEqual,
        MaterialImplication,
        Maximum,
        Minimum,
        Multiplication,
        Negation,
        Subtraction,
        Remainder
    }
}